### ISSUE TITLE
Play symbol not rendering on Android

### ISSUE THREAD

**Issue by jspenger** [portals-project/playground#1]
The play symbol on the Playground website https://www.portals-project.org/playground/ does not render on Android phones. The underlying issue seems to be that the symbol `&#9205;` is not supported in android fonts, and it is also not covered in the fonts used on the website https://www.fileformat.info/info/unicode/char/23f5/fontsupport.htm. 

* [ ] Suggest some alternative play symbols (that you've checked work)
* [ ] Integrate the new play symbol

**Comment by MKLepium** [comment]
https://www.compart.com/en/unicode/U+25B6

This character appears to be working as well on my phone (Samsung A52, Android) and on all of my browsers (Firefox, Google Chrome, Edge)
