### ISSUE TITLE
Log output scroll fixes to bottom if run is repeatedly pressed

### ISSUE THREAD

**Issue by jspenger** [portals-project/playground#9]
The Log Output scroll fixes to the bottom after the Run button is pressed twice at a short time interval.

How to reproduce:
* Go to the playground: https://www.portals-project.org/playground/
* Open the "Map" example
* Spam-press the Run button twice, at a short time interval (but not too short)
* The scroll is now fixed at the bottom, and it is not possible to scroll up, it keeps jumping down to the last line

This should be fixed. Instead, the log should not be fixed to the bottom, and it should be possible to scroll up.

* Remove the scroll auto-fixation to the bottom.

**Comment by GGmorello** [comment]
Quick update 
I tried to remove the scroll to the last line, it didn't solve the issue.
I tried to move the setting of the running flag earlier in the code, it didn't solve the issue.
I tried to add a debounce function to the event listener, it solved the issue but other errors arose, I need to investigate this last solution more

**Comment by jspenger** [comment]
If there is no easy solution for this, then I would move onto some other issues for now; we will complete this issue later once we have done more important work.

**Comment by aversey** [comment]
The solution was quite easy, instead of clearing null:
```
loggingInterval = null;
clearInterval(loggingInterval);
```
There should be clearing of the interval:
```
clearInterval(loggingInterval);
loggingInterval = null;
```
=)
